In [1]:
import torch
import numpy as np

In [2]:
data = [[1, 2], [3, 4]]
data_tensor = torch.tensor(data)
#torch.tensor is used to convert to tensor
print(data_tensor, type(data_tensor))

tensor([[ 1,  2],
        [ 3,  4]]) <class 'torch.Tensor'>


In [3]:
data = [[1, 2], [3, 4], [5, 6]]
np_data = np.array(data)
print(np_data, type(np_data))
np_data_tensor = torch.from_numpy(np_data)
#torch.from_numpy is used to convert a numpy array to tensor
print(np_data_tensor, type(np_data_tensor))

[[1 2]
 [3 4]
 [5 6]] <class 'numpy.ndarray'>
tensor([[1, 2],
        [3, 4],
        [5, 6]]) <class 'torch.Tensor'>


In [3]:
torch.zeros(5)
#to create a tensor of zeros with given shape

tensor([ 0.,  0.,  0.,  0.,  0.])

In [4]:
torch.ones(2, 2)
#to create a tensor of ones with given shape

tensor([[ 1.,  1.],
        [ 1.,  1.]])

In [5]:
torch.rand(3, 3, 3)
#to create a tensor of randoms between [0,1] with given shape

tensor([[[ 0.7280,  0.2821,  0.8295],
         [ 0.6282,  0.7441,  0.9750],
         [ 0.1575,  0.6537,  0.7536]],

        [[ 0.7279,  0.2601,  0.1827],
         [ 0.5107,  0.0911,  0.8828],
         [ 0.4536,  0.9171,  0.6364]],

        [[ 0.9000,  0.0470,  0.6206],
         [ 0.5785,  0.3466,  0.3272],
         [ 0.4217,  0.6749,  0.7614]]])

In [6]:
zero_tensor = torch.zeros(3, 3)
ones_like_zeros = torch.ones_like(zero_tensor)
#torch.ones_like used to create a tensor with the shape of existing tensor but it contains all zeros
print(zero_tensor.shape, ones_like_zeros.shape)

torch.Size([3, 3]) torch.Size([3, 3])


In [7]:
zero_tensor[0]

tensor([ 0.,  0.,  0.])

In [8]:
ones_like_zeros[:, 0]

tensor([ 1.,  1.,  1.])

In [9]:
x = ones_like_zeros.detach()
print(x)
#.detach() is used to create a copy of tensor but not attached to the graph.
#The grpah is used by auto grad to propagate gradient
#Basically it creates a copy of tensor outside the model

tensor([[ 1.,  1.,  1.],
        [ 1.,  1.,  1.],
        [ 1.,  1.,  1.]])


In [10]:
x[:, 0] * 5
#scalar multiplication

tensor([ 5.,  5.,  5.])

In [24]:
print(x[0,:],x[0,:].shape)
print(x[:, 0],x[:, 0].shape)

tensor([ 1.,  1.,  1.]) torch.Size([3])
tensor([ 1.,  1.,  1.]) torch.Size([3])


In [22]:
rand1 = torch.rand(5)
rand2 = torch.rand(5)
torch.matmul(rand1, rand2)
#torch.matmul is used to find dot product of tensors

tensor(1.0843)

In [23]:
rand1 = torch.rand(5, 5)
rand2 = torch.rand(5, 5)
torch.matmul(rand1, rand2)

tensor([[ 1.3469,  2.2363,  2.0420,  1.3650,  0.6972],
        [ 0.9983,  1.6469,  1.5681,  1.0488,  0.6772],
        [ 1.7232,  2.6531,  2.8101,  2.2396,  1.0839],
        [ 1.0425,  1.7815,  1.8375,  1.4776,  0.7466],
        [ 1.3356,  2.0908,  2.3152,  1.8914,  1.0941]])